Portal/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Portal.DeploymentService.Interface;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Portal.Pages
{
    // [Authorize]
    [IgnoreAntiforgeryToken]
    public class IndexModel : PageModel
    {
        private readonly IDeploymentService _deploymentService;
        private readonly ILogger<IndexModel> _logger;
        private readonly IConfiguration _configuration;

        public string UserIpAddress { get; private set; } = string.Empty;
        public IList<string> UsersContainer { get; set; } = new List<string>();

        [BindProperty]
        [Required(ErrorMessage = "Instance ID is required.")]
        public string InstanceId { get; set; } = string.Empty;

        public List<ExerciseConfig> Exercises { get; set; } = new();
        public string UserName { get; private set; } = string.Empty;
        private string _uid = string.Empty;

        public IndexModel(IDeploymentService deploymentService, ILogger<IndexModel> logger, IConfiguration configuration)
        {
            _deploymentService = deploymentService;
            _logger = logger;
            _configuration = configuration;
        }

        public async Task OnGetAsync()
        {
            InitializeUserContext();
            UsersContainer = await _deploymentService.ListUsersContainer(_uid);
            Exercises = LoadExercises();
            _logger.LogInformation("User {UserName} with uid {Uid} accessed the portal.", UserName, _uid);
        }

        public async Task<IActionResult> OnPostDeployInstanceAsync(string exerciseName)
        {
            if (string.IsNullOrWhiteSpace(exerciseName))
            {
                ModelState.AddModelError(string.Empty, "Exercise name is required.");
                return Page();
            }

            _logger.LogInformation("Deploying container for exercise: {ExerciseName}", exerciseName);

            try
            {
                await DeployContainerAsync(exerciseName);
                return RedirectToPage("Containers/GetContainerDetails", new { exerciseName });
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error deploying container for exercise: {ExerciseName}", exerciseName);
                ModelState.AddModelError(string.Empty, "An error occurred while deploying the container. Please try again.");
                return Page();
            }
        }

        public async Task<IActionResult> OnPostStopInstanceAsync(string exerciseName)
        {
            if (string.IsNullOrWhiteSpace(exerciseName))
            {
                ModelState.AddModelError(string.Empty, "Exercise name is required.");
                return Page();
            }

            _logger.LogInformation("Stopping container for exercise: {ExerciseName}", exerciseName);

            try
            {
                var containerDetails = await _deploymentService.FetchContainerDetails(exerciseName, new List<string> { "ID" }, _uid);
                var instanceId = containerDetails.ID;

                await _deploymentService.RemoveUserOrPauseContainer(instanceId, _uid);
                _logger.LogInformation("Container stopped: {InstanceId}", instanceId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Failed to stop container for exercise: {ExerciseName}", exerciseName);
                ModelState.AddModelError(string.Empty, "There was an error stopping the container. Please try again later.");
            }

            return RedirectToPage();
        }

        private async Task DeployContainerAsync(string exerciseName)
        {
            InitializeUserContext();

            var exerciseConfig = Exercises.FirstOrDefault(e => e.ExerciseName.Equals(exerciseName, StringComparison.OrdinalIgnoreCase));
            if (exerciseConfig == null)
            {
                throw new ArgumentException("Invalid exercise name provided.");
            }

            LogExerciseConfigurations();
            _logger.LogInformation("loging vars yaya");
                // log values in Variables
            foreach (var item in exerciseConfig.Variables)
            {
                _logger.LogInformation("Key: {Key}, Value: {Value}", item.Key, item.Value);
            }

            string containerId = await _deploymentService.GetOrCreateContainerForUser(
                exerciseConfig.DockerImage,
                exerciseConfig.ExerciseName,
                _uid,
                exerciseConfig.port ?? string.Empty,
                UserIpAddress,
                exerciseConfig.ClientSide,
                exerciseConfig.ClientPort,
                exerciseConfig.MaxUsers,
                exerciseConfig.Variables);

            try
            {
                HttpContext.Session.SetString("CreatedContainerId", containerId);
                _logger.LogInformation("Container deployed successfully with ID: {ContainerId}", containerId);
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Error storing container ID in session.");
                throw new Exception("Unable to store container ID in session.", ex);
            }
        }

        private  void InitializeUserContext()
        {
            _uid = User.FindFirst("uid")?.Value ?? string.Empty;
            UserName = User.FindFirst("name")?.Value?.Split(',').FirstOrDefault()?.Split(' ').FirstOrDefault() ?? string.Empty;
            Exercises = LoadExercises();
            UserIpAddress = GetUserIpAddress();

        }

        private List<ExerciseConfig> LoadExercises()
        {
            var exercises = new List<ExerciseConfig>();
            var configDirectory = _configuration.GetValue<string>("ExerciseConfigDirectory") ?? "ExConfiguration";

            foreach (var filePath in Directory.GetFiles(configDirectory, "*.json"))
            {
                var config = new ExerciseConfig();
                var fileConfig = new ConfigurationBuilder()
                    .AddJsonFile(filePath)
                    .Build();
                fileConfig.Bind(config);
                exercises.Add(config);
            }

            return exercises;
        }

        private string GetUserIpAddress()
        {
            if (Request.Headers.ContainsKey("X-Forwarded-For"))
            {
                var ip = Request.Headers["X-Forwarded-For"].FirstOrDefault()?.Split(',').FirstOrDefault();
                _logger.LogInformation("User IP from X-Forwarded-For: {UserIpAddress}", ip);
                return ip ?? "192.168.64.1";
            }

            var remoteIp = HttpContext.Connection.RemoteIpAddress?.ToString();
            if (!string.IsNullOrEmpty(remoteIp) && remoteIp != "::1")
            {
                _logger.LogInformation("User IP from RemoteIpAddress: {UserIpAddress}", remoteIp);
                return remoteIp;
            }

            _logger.LogInformation("Default User IP: {UserIpAddress}", "192.168.64.1");
            return "192.168.64.1";
        }

        private void LogExerciseConfigurations()
        {
            foreach (var ex in Exercises)
            {
                _logger.LogInformation("Exercise: {ExerciseName}, Image: {DockerImage}, Port: {Port}, ClientSide: {ClientSide}, ClientPort: {ClientPort}, MaxUsers: {MaxUsers}",
                    ex.ExerciseName, ex.DockerImage, ex.port, ex.ClientSide, ex.ClientPort, ex.MaxUsers);
            }
        }
    }
}

Portal/Pages/Index.cshtml
@page
@model Portal.Pages.IndexModel
@{
    ViewData["Title"] = "Home Page";
}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Portal</title>
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet" />
        <link href="~/css/homePage.css" rel="stylesheet" />

</head>

<body>
    <div class="container mt-5">
        <div class="text-center mb-5">
            <h1 class="display-25">Welcome @Model.UserName</h1>
        </div>

        <div class="exercise-list-container">
            <h1 class="exercise-list-title">Exercise List</h1>
            <div class="row">
                @foreach (var exercise in Model.Exercises)
                {
                    <div class="col-md-4 mb-4">
                        <div class="card exercise-card h-100" id="exercise-@exercise.ExerciseName">
                            <div class="card-body d-flex flex-column">
                                <h5 class="card-title d-flex align-items-center justify-content-start gap-2 text-left">
                                    @exercise.ExerciseTile
                                    @if (exercise.ClientSide == false)
                                    {
                                        <img src="~/assets/client.png" alt="Client" class="img-fluid"
                                            style="width: 40px; height: 40px;" />
                                    }
                                    else
                                    {
                                        <img src="~/assets/Server.png" alt="Server" class="img-fluid"
                                            style="width: 40px; height: 40px;" />
                                    }
                                </h5>

                                <p class="card-text">@exercise.ExerciseDescription</p>
                                <p class="card-text"><small class="text-muted">Difficulty:
                                        @exercise.ExerciseDifficulty</small></p>
                                <div class="mt-auto pt-3 d-flex justify-content-center exercise-actions">
                                    @if (Model.UsersContainer.Contains(exercise.DockerImage))
                                    {
                                        <form method="post" asp-page-handler="DeployInstance" class="mr-2"
                                            id="resume-form-@exercise.ExerciseName">
                                            <input type="hidden" name="ExerciseName" value="@exercise.ExerciseName" />
                                            <button class="btn btn-outline-primary" type="submit"
                                                id="resume-btn-@exercise.ExerciseName">Resume</button>
                                        </form>
                                        <form method="post" asp-page-handler="StopInstance"
                                            id="stop-form-@exercise.ExerciseName">
                                            <input type="hidden" name="ExerciseName" value="@exercise.ExerciseName" />
                                            <button class="btn btn-outline-danger" type="submit"
                                                id="stop-btn-@exercise.ExerciseName">Stop</button>
                                        </form>
                                    }
                                    else
                                    {
                                        <form method="post" asp-page-handler="DeployInstance"
                                            id="start-form-@exercise.ExerciseName">
                                            <input type="hidden" name="ExerciseName" value="@exercise.ExerciseName" />
                                            <button class="btn btn-outline-success" type="submit"
                                                id="start-btn-@exercise.ExerciseName">Start</button>
                                        </form>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>

    <!-- Scripts -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
        integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-pzjw8f+ua7Kw1TIqE7anJf6b3zH5pbeVxknzYlbR5STIbYQb6P6afkFeJQuo5eNm"
        crossorigin="anonymous"></script>
    <script src="~/js/site.js"></script>
</body>

</html>